#!/usr/bin/env bash
HEAD="_HEAD.md"
TAIL="_TAIL.md"
README="README.md"

# Reformat
./terraform fmt

# NOTE: If the order of the keys in the `links` variable is changed,
# it is not guaranteed that the `aws_api_gateway_resource` resources
# will be regenerated after all resources being destroyed.
# If you try to create the same name as a resource that has not
# yet been destroyed, you will have problems.
# So I intended to destroy all `aws_api_gateway_resource`
# with `terraform destroy` command.(This is not a good way)
destroy_aws_api_gateway_resources_will_modified () {
    TEMP_FILE=".temp_plan_output"

    ./terraform plan > "$TEMP_FILE"
    resources=$(grep -Pao '[+-~].+module\.links\.aws_api_gateway_resource.links\[\d+\]' "$TEMP_FILE")

    echo "$resources"
    # shellcheck disable=SC2086
    (echo "$resources" | grep -q "module.links.aws_api_gateway_resource.links") &&\
        (./terraform destroy -auto-approve -target="aws_api_gateway_resource.links") ||\
        return 1

    rm -f "$TEMP_FILE"

    return 0
}

./terraform init --upgrade &&\
    destroy_aws_api_gateway_resources_will_modified &&\
    ./terraform plan -out="terraform.tfplan" &&\
    ./terraform apply "terraform.tfplan" &&\
    rm "terraform.tfplan"

# Update README.md: table of links
links=$(grep -Pzo 'links = {[^}]+}' "main.tf" |\
    grep -Pao '[^#]\s+"([^ ]+)"\s+= "(.+)"$' |\
    sed 's/"//g' |\
    sed -r 's/ //g' |\
    sed -r 's/=/|/g')

echo "### List of all links" > "$TAIL"
echo "| Link | URL |" >> "$TAIL"
echo "| - | - |" >> "$TAIL"

for l in $links
do
    link=$(echo "$l" | cut -d '|' -f 1)
    url=$(echo "$l" | cut -d '|' -f 2)
    echo "| $link | $url |" >> "$TAIL"
done

# Merge markdown files
cat "$HEAD" > "$README"
echo '' >> "$README"
cat "$TAIL" >> "$README"

echo "* All complete! Please check git status and commit."
